version: '3.8'

services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
