export const userMessagePatterns = {
  createUser: { cmd: 'createUser' },
  getUser: { cmd: 'getUser' },
  updateUser: { cmd: 'updateUser' },
  getUsers: { cmd: 'getUsers' },
  addFriend: { cmd: 'addFriend' },
  deleteUser: { cmd: 'deleteUser' },
  removeFriend: { cmd: 'removeFriend' },
  checkIfFriends: { cmd: 'checkIfFriends' },
  getUserWithFriend: { cmd: 'getUserWithFriend' },
  uploadUserImage: { cmd: 'uploadUserImage' },
  getUserImage: { cmd: 'getUserImage' },
  deleteUserImage: { cmd: 'deleteUserImage' },
  updateUserImage: { cmd: 'updateUserImage' },
  getUserForItemUpdate: { cmd: 'getUserForItemUpdate' },
  getUserByEmail: { cmd: 'getUserByEmail' },
};
